//Create a Class Employee with the following specifications

//Properties
//----------
//string Name -> no blank names should be allowed
//int EmpNo ->  must be readonly and autogenerated
//decimal Basic -> must be between some range
//short DeptNo -> must be > 0

//Methods
//-------
//decimal GetNetSalary() -> returns calculated net salary (Use any formula to get net salary based on Basic salary)


//Create constructors to accept initial values for Employee obj
//Employee o1 = new Employee("Amol", 123465, 10);

//Employee o2 = new Employee("Amol", 123465);
//Employee o3 = new Employee("Amol");
//Employee o4 = new Employee();

//EmpNo must be autogenerated ... i.e.
//first object should automatically get EmpNo 1
//second object should automatically get EmpNo 2
//third object should automatically get EmpNo 3
//...and so on...

//Test Cases
//Employee o1 = new Employee()
//Employee o2 = new Employee()
//Employee o3 = new Employee()
//cw(o1.EmpNo)
//cw(o2.EmpNo)
//cw(o3.EmpNo)

//cw(o3.EmpNo)
//cw(o2.EmpNo)
//cw(o1.EmpNo)



namespace Employee
{
    internal class Program
    {
        static void Main(string[] args)
        {
            //Employee e = new Employee();
            //e.Name = "Krishna";
          
            //e.Basic = 20000;
            //e.DeptNo = 12;
            ////e.prop1 = "";
            //Console.WriteLine($"name of the employee is {e.Name}");
            //Console.WriteLine( $"{e.EmpNo}");
            //Console.WriteLine($"basi salary of the employee is {e.Basic}");
            //Console.WriteLine($"net salary of the employees is{e.getNetsalary()}");
            //Console.WriteLine($"dept not of the employess is {e.DeptNo}");

            Employee o1 = new Employee();
            Employee o2 = new Employee("Amol", 123465);
            Employee o3 = new Employee("Amol");
            Employee o4 = new Employee();
          
            Console.WriteLine(o1.EmpNo);
            Console.WriteLine(o2.EmpNo);
            Console.WriteLine(o3.EmpNo);

            Console.WriteLine(o3.EmpNo);
            Console.WriteLine(o2.EmpNo);
            Console.WriteLine(o1.EmpNo);

        }
    }
    public class Employee
    {
   
        private string name;
        private int empNo;
        private decimal basic;
        private short deptNo;
        public string Name
        {
            set
            {
                if (value != "")
                {
                    name = value;
                }
                else
                {
                    Console.Write("invalid!");
                }
            }
            get
            {
                return name;
            }


        }
        private static int temp=0;
       
           
     
        public int EmpNo
        {
            get
            {
                return empNo;
            }
        }

        // public Employee()
        //{
          
        //    empNo=empNo+1;
        //}
        
        
        public decimal Basic
        {
            set
            {
                if (value < 100000 && value > 1000)
                {
                    basic = value;
                }
                else
                {
                    Console.WriteLine("Invalid!");
                }
            }
            get
            {
                return basic;
            }
        }
        public decimal getNetsalary()
        {
            decimal netSalary;
            netSalary = basic - 2000;
            return netSalary;
        }

        public short DeptNo
        {
            set
            {
                if (value > 0)
                {
                    deptNo = value;
                }
                else
                {
                    Console.WriteLine("Invalid");
                }
            }
            get
            {
                return deptNo;
            }
        }
      
        public Employee(string name="" ,decimal basic=0, short deptno=0)
        {
            temp++;
            empNo = temp;
            this.name = name;
            this.basic = basic; 
            this.deptNo = deptno;       
        }
    }
}
